
```{r}
# Carregamento dos dados do estudo
library(cBioPortalData)
id = "paad_qcmg_uq_2016"
paad = cBioDataPack(id)
```

```{r}
# Verificar se objeto foi carregado corretamente
experiments(paad)
```
```{r}
# Explorar conteúdo do objeto
assays(paad)
names(assays(paad))
```
Trecho sobre normalização

"For downstream analyses, normalized RSEM data were converted to counts per million (c.p.m.) and log2 transformed35. Genes without at least 1 c.p.m. in 20% of the sample were excluded from further analysis." [ref](https://www.nature.com/articles/nature16965)

```{r}
# Data set já contém dados standardizados, iremos utilizar esses dados
# ensaio nome "mrna_seq_v2_rsem_zscores_ref_all_samples"
# os dados apresentados já estão normalizados em CPM de acordo com os autores


paad_expr_data = as.data.frame(
  assays(paad)["mrna_seq_v2_rsem_zscores_ref_all_samples"]$mrna_seq_v2_rsem_zscores_ref_all_samples
)
#head(paad_expr_data)
#tail(paad_expr_data)

# Verificamos existencia de valores omissos
# Criamos uma função para poder reutilizar

remove_na <- function(df) {
  
  if (any(is.na(df))) {
    
    df <- na.omit(df)
  }

  return(df)
}

paad_expr_data = remove_na(paad_expr_data)

```

```{r}
# carregamento de metadados
# verificação de dados omissos

meta_paad = as.data.frame(
  colData(paad)
)

#head(meta_paad)
#tail(meta_paad)

```

```{r}
# Proponho análise comparativa por tumour grade (hábitos de fumo tb podem ser interessantes)

# Vamos remover todas as outras colunas e manter apenas sample_id e tumour grade
which(names(meta_paad) %in% c("SAMPLE_ID","TUMOR_GRADE"))
meta_paad = meta_paad[,c(2,5)]

meta_paad = remove_na(meta_paad)
meta_paad
```


```{r}

# Verif. se todas as samples estão representadas
length(colnames(paad_expr_data)) == length(meta_paad$SAMPLE_ID)
length(colnames(paad_expr_data))

# Nem todas as amostras estão incluídas na expressão genética por isso é necessário aparar os metadados
meta_paad = subset(meta_paad, meta_paad$SAMPLE_ID %in% colnames(paad_expr_data))

# Verificamos o sucesso da operação
length(colnames(paad_expr_data)) == length(meta_paad$SAMPLE_ID)

# Verificamos se a ordem é a mesma
all(colnames(paad_expr_data) == meta_paad$SAMPLE_ID)

# Não é por isso precisamos reorganizar

paad_expr_data = paad_expr_data[,meta_paad$SAMPLE_ID]

# Verificamos o sucesso
all(colnames(paad_expr_data) == meta_paad$SAMPLE_ID)
```

```{r}
library(edgeR)

sum(paad_expr_data < 0)

```

