---
title: "Grupo 4 - Pancreas Adeno Carcinoma"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    theme: spacelab
    number_sections: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---
<style>
  body {text-align:justify}
</style>


[Referência para CBioPortal API](https://cbioportal.github.io/2020-cbioportal-r-workshop/)
[Demonstração de utilização de objetos multiassay e estudos do CBio](https://cbioportal.github.io/2020-cbioportal-r-workshop/Example2.pdf)
[Mais documentação sobre MAE API](https://github.com/waldronlab/MultiAssayExperiment/wiki/MultiAssayExperiment-API)


```{r}
#' Instalar packages
#' Descomentar para instalar
#'
#'if (!requireNamespace("BiocManager", quietly = TRUE))
#'    install.packages("BiocManager")
#'
#'if (!requireNamespace("cBioPortalData", quietly = TRUE))
#'    BiocManager::install("cBioPortalData")
#'    
#'    BiocManager::install("MultiAssayExperiment")
#'    BiocManager::install("curatedTCGAData")
#'    BiocManager::install("TCGAutils")
#'    install.packages("UpSetR")
```
```{r}
# Carregar packages
library(cBioPortalData)
library(httr)
library(dplyr)
library(ggplot2)
library(MultiAssayExperiment)
library(S4Vectors)
library(UpSetR)

# Carregar API

cbio <- cBioPortal()

# Definir ID do estudo (ver link)

id = "paad_qcmg_uq_2016"

# Carregar os dados do estudo como MultiAssayExperiment 

paad = cBioDataPack(id)
```
```{r}


#Explorar o ficheiro

experiments(paad)

assays(paad) # Identificar id do ensaio de expressão


# Isolar dados
expr = assays(paad)['mrna_seq_v2_rsem'] 
expr = as.data.frame(expr$mrna_seq_v2_rsem)
expr

meta = as.data.frame(colData(paad))
meta



```


```{r}
expr
meta

```


```

